name: capture_metrics
description: Parses results.json into a TrainingResults object

task_type: predefined
handler: agent.handlers.capture_metrics

config:
  required_metrics:
    - roc_auc_macro
    - loss
  compute_deltas_vs_best: true
